questions =  [
    {"id": 0, "question": "Freedom of business is the best practical way a society can prosper.", "effects": {"right": 1}},
    {"id": 1, "question": "Charity is a better way of helping those in need than social welfare.", "effects": {"right": 1}},
    {"id": 2, "question": "There should be regulations placed on a business's wages.", "effects": {"right": -1}},
    {"id": 3, "question": "It is human nature to be greedy.", "effects": {"right": 1}},
    {"id": 4, "question": "\"Exploitation\" is an outdated term, as the struggles of 1800s capitalism don't exist anymore.", "effects": {"right": 1}},
    {"id": 5, "question": "Communism is an ideal that can never work in practice.", "effects": {"right": 1}},
    {"id": 6, "question": "Taxation of the wealthy should remain highly limited, or be reduced.", "effects": {"right": 1}},
    {"id": 7, "question": "The harder you work, the more you progress up the social ladder.", "effects": {"right": 1}},
    {"id": 8, "question": "Organisations and corporations cannot be trusted and need to be regulated by the government.", "effects": {"right": -1}},
    {"id": 9, "question": "A government that provides for everyone is an inherently good idea.", "effects": {"right": -1}},
    {"id": 10, "question": "The current welfare system should be expanded to further combat poverty.", "effects": {"right": -1}},
    {"id": 11, "question": "Land should not be a commodity to be bought and sold.", "effects": {"right": -1}},
    {"id": 12, "question": "All industry and the bank should be publically owned.", "effects": {"right": -1}},
    {"id": 13, "question": "Class is the primary division of society.", "effects": {"right": -1}},
    {"id": 14, "question": "Economic inequality is a real problem that must be combated.", "effects": {"right": -1}},
    {"id": 15, "question": "Sometimes it is right that the government may spy on its citizens to combat extremists and terrorists, warrantless.", "effects": {"auth": 1}},
    {"id": 16, "question": "Authority figures, if morally correct, are a good thing for society.", "effects": {"auth": 1}},
    {"id": 17, "question": "Strength is necessary for any government to succeed.", "effects": {"auth": 1}},
    {"id": 18, "question": "Only the government can fairly and effectively regulate organisations.", "effects": {"auth": 1}},
    {"id": 19, "question": "Society requires structure and bureaucracy in order to function.", "effects": {"auth": 1}},
    {"id": 20, "question": "Mandatory IDs should be used to ensure public safety.", "effects": {"auth": 1}},
    {"id": 21, "question": "In times of crisis, safety becomes more important than civil liberties.", "effects": {"auth": 1}},
    {"id": 22, "question": "If you have nothing to hide, you have nothing to fear.", "effects": {"auth": 1}},
    {"id": 23, "question": "The government should be less involved in the day to day life of its citizens.", "effects": {"auth": -1}},
    {"id": 24, "question": "Policies that are intrusive or restrictive on people's personal business are generally bad.", "effects": {"auth": -1}},
    {"id": 25, "question": "Jury nullification should be legal.", "effects": {"auth": -1}},
    {"id": 26, "question": "The more limited the government is on people's personal lives, the freer the people.", "effects": {"auth": -1}},
    {"id": 27, "question": "The government should not regulate private, non-violent, personal activities, even if I disapprove of them.", "effects": {"auth": -1}},
    {"id": 28, "question": "The police was not made to protect the people, but to uphold the status-quo by force.", "effects": {"auth": -1}},
    {"id": 29, "question": "The state shouldn't be influencing our children.", "effects": {"auth": -1}},
    {"id": 30, "question": "What one does with their own body cannot be immoral if it doesn't harm another person.", "effects": {"prog": 1}},
    {"id": 31, "question": "Homosexuals and transgenders should have equal adoption rights to everyone else.", "effects": {"prog": 1}},
    {"id": 32, "question": "All cultures and peoples are equal.", "effects": {"prog": 1}},
    {"id": 33, "question": "Nudism is perfectly natural and okay.", "effects": {"prog": 1}},
    {"id": 34, "question": "Animals deserve certain universal rights.", "effects": {"prog": 0.5}},
    {"id": 35, "question": "Gender is a social construct, not a natural state of affairs.", "effects": {"prog": 1}},
    {"id": 36, "question": "There is nothing morally wrong with the consumption or creation of pornography depicting consensual adults.", "effects": {"prog": 0.5}},
    {"id": 37, "question": "Autonomy of body extends even to minors, the mentally ill, and serious criminals.", "effects": {"prog": 1}},
    {"id": 38, "question": "Same sex marriage should be permitted.", "effects": {"prog": 1}},
    {"id": 39, "question": "Homosexuality is against my values.", "effects": {"prog": -1}},
    {"id": 40, "question": "Drugs are harmful and immoral.", "effects": {"prog": -0.5}},
    {"id": 41, "question": "The death penalty should exist for certain crimes.", "effects": {"prog": -1}},
    {"id": 42, "question": "It is important that borders exist, and that immigration should be regulated.", "effects": {"prog": -1}},
    {"id": 43, "question": "One cannot be moral without religion.", "effects": {"prog": -1}},
    {"id": 44, "question": "Parents should hold absolute power over their children, as they are older and more experienced.", "effects": {"prog": -1}},
    {"id": 45, "question": "Multiculturalism is bad.", "effects": {"prog": -1}},
    {"id": 46, "question": "Discipline is the most important trait in a person..", "effects": {"prog": -0.5}}
    {"id": 47, "question": "Democracy is retarded.", "effects": {"prog": -1}}
];
